name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (or your project framework)
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Adjust if you use a different version

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: |
        echo "REACT_APP_API_KEY=${{ secrets.MY_API_KEY }}" > .env
        npm run build  # Adjust this based on your build process

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./build  # Or wherever your build output is
        user_name: 'github-actions'
        user_email: 'github-actions@users.noreply.github.com'
