name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate API Key File
        run: |
          # Create a basic "encryption" of the API key (base64)
          ENCODED_KEY=$(echo -n ${{ secrets.MY_API_KEY }} | base64)
          echo "const ENCRYPTED_KEY = '$ENCODED_KEY';" > v1/api-key.js
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: v1 # The folder to deploy